// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLmpJvfKJ62ptX1-XAa8joUivObD2cw-M',
    appId: '1:304784617031:web:a2c7b094cb5ca706788b62',
    messagingSenderId: '304784617031',
    projectId: 'hurey-app',
    authDomain: 'hurey-app.firebaseapp.com',
    storageBucket: 'hurey-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEO6VgogaCARml0ZQrDrKMJju9wv6A4pw',
    appId: '1:304784617031:android:a78ad857efa54196788b62',
    messagingSenderId: '304784617031',
    projectId: 'hurey-app',
    storageBucket: 'hurey-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXdC5h5b_oJaJCWVIvp9g6daCVj0QMGM',
    appId: '1:304784617031:ios:4c006434392d6364788b62',
    messagingSenderId: '304784617031',
    projectId: 'hurey-app',
    storageBucket: 'hurey-app.firebasestorage.app',
    iosBundleId: 'com.example.hurreyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXdC5h5b_oJaJCWVIvp9g6daCVj0QMGM',
    appId: '1:304784617031:ios:4c006434392d6364788b62',
    messagingSenderId: '304784617031',
    projectId: 'hurey-app',
    storageBucket: 'hurey-app.firebasestorage.app',
    iosBundleId: 'com.example.hurreyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLmpJvfKJ62ptX1-XAa8joUivObD2cw-M',
    appId: '1:304784617031:web:244f5752624785a4788b62',
    messagingSenderId: '304784617031',
    projectId: 'hurey-app',
    authDomain: 'hurey-app.firebaseapp.com',
    storageBucket: 'hurey-app.firebasestorage.app',
  );
}
